name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Docker login
      run: docker login ghcr.io --username damikael --password ${{secrets.DOCKER_CI_TOKEN}}
      
    - name: Build the Docker image
      run: docker build . --file setup/Dockerfile --tag spid-php:latest

    - name: Docker Tag
      run: docker tag spid-php:latest ghcr.io/italia/spid-php:latest

    - name: Docker Push to GitHub Registry
      run: docker push ghcr.io/italia/spid-php:latest
